# Generated by Django 5.2 on 2025-04-23 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('address', models.CharField(max_length=150)),
                ('birthdate', models.DateField()),
                ('skills', models.TextField()),
                ('tel', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('selectionCriteria', models.TextField()),
                ('datePub', models.DateField()),
                ('city', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('doc', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRFlow.application')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=150)),
                ('job', models.CharField(max_length=150)),
                ('hireDate', models.DateField()),
                ('absences', models.IntegerField(default=0)),
                ('availableLeave', models.IntegerField(default=30)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='HRFlow.dept')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HRFlow.employee')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('justification', models.TextField()),
                ('mode', models.CharField(max_length=150)),
                ('sent', models.BooleanField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRFlow.employee')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='jobOffer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRFlow.joboffer'),
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('justification', models.TextField()),
                ('accepted', models.BooleanField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRFlow.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Trainning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('startDate', models.DateField()),
                ('duration', models.IntegerField()),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='HRFlow.dept')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='trainningParticipations',
            field=models.ManyToManyField(related_name='participations', to='HRFlow.trainning'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=150)),
                ('familyName', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=150)),
                ('applications', models.ManyToManyField(through='HRFlow.Application', to='HRFlow.joboffer')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('checked', models.BooleanField(default=False)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRFlow.user')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HRFlow.user'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRFlow.user'),
        ),
    ]
