# Generated by Django 5.2 on 2025-04-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRFlow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='isHR',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('REJ', 'rejected'), ('ACC', 'accepted'), ('REC', 'received'), ('APP', 'applied'), ('T.T', 'technical test'), ('INT', 'interview')], max_length=3),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('R', 'resume'), ('L', 'cover letter'), ('O', 'other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='documentdemande',
            name='mode',
            field=models.CharField(choices=[('E', 'email'), ('S', 'sms'), ('M', 'message'), ('P', 'print')], max_length=1),
        ),
        migrations.AlterField(
            model_name='documentdemande',
            name='type',
            field=models.CharField(choices=[('EC', 'employment contract'), ('WC', 'work certificate'), ('PS', 'payslip')], max_length=2),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='category',
            field=models.CharField(choices=[('S', 'on-site'), ('H', 'hybrid'), ('R', 'remote')], max_length=1),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='type',
            field=models.CharField(choices=[('CDI', 'cdi'), ('CDD', 'cdd'), ('INT', 'internship')], max_length=3),
        ),
        migrations.AlterField(
            model_name='leave',
            name='type',
            field=models.CharField(choices=[('S', 'sickness'), ('R', 'rtt'), ('P', 'payed')], max_length=1),
        ),
    ]
